# .gitlab-ci.yml for generating a Jekyll based site.
#
# Based on the example from
#    https://gitlab.com/pages/jekyll/blob/master/.gitlab-ci.yml
image: ruby:latest

variables:
  JEKYLL_ENV: production

before_script:
  - gem install bundler
  - bundle install

pages:
  stage: deploy
  script:
   - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - ctcms
