# Travis-CI config for https://github.com/hpc-carpentry/hpc-intro
# Results at https://travis-ci.org/github/hpc-carpentry/hpc-intro

dist: xenial
language: python
python: 3.7

branches:
  only:
  - gh-pages
  - /.*/

jobs:
  include:
    # Check spelling before building the site to fail quicker.
    - stage: "Check for typos and spelling mistakes"
      before_install: # Don't need everything to build the site
      install:
        pip install codespell
      script:
    - stage: "Build the site"

before_install:
  - sudo apt-get update -y
  - rvm default
  - gem install bundler jekyll json kramdown
  - bundle install

install:
  - pip install codespell pyyaml

script:
  - make lesson-check-all
  - make --always-make site
