# Travis-CI config for https://github.com/hpc-carpentry/hpc-intro
# Results at https://travis-ci.org/github/hpc-carpentry/hpc-intro

dist: xenial
language: python
python: 3.7

branches:
  only:
  - gh-pages
  - /.*/

before_install:
  - sudo apt-get update -y
  - rvm default
  - gem install bundler jekyll json kramdown
  - bundle install

install:
  - pip install pyyaml

script:
  - make --always-make site

jobs:
  include:
    - stage: "Check for typos and spelling mistakes"
      install:
        pip install codespell
      script:
        codespell --skip="assets,*.svg,bin" --quiet-level=2  -L "rouge,dropse,namd,hist"
    - stage: "Check consistency of style"
      script:
        make lesson-check-all
    - stage: "Build the site"
