# EPCC, The University of Edinburgh: Cirrus + PBS Pro
host: "Cirrus"
login_host: "login.cirrus.ac.uk"
host_location: "EPCC, The University of Edinburgh"
host_homedir: "/lustre/home/tc001/lola"
host_prompt: "[yourUsername@cirrus-login0 ~]$"
sched_name: "PBS Pro"
sched_submit: "qsub"
sched_submitopt: "-A tc001 -q R387726"
sched_stat: "qstat"
sched_uopt: "-u yourUsername"
sched_del: "qdel"
sched_submiti: "qsub"
sched_submitiopt: "-IVl select=1:ncpus=1"
sched_info: "pbsnodes -a"
sched_comment: "#PBS"
sched_nameopt: "-N"
sched_hist: "qstat -x"
sched_histdetail: "-f"
